"""
Curated domain vocabularies (manual priors). Extend LEGAL_KEYWORDS when Legal is added.
"""
from __future__ import annotations

from .config import DOMAINS

# Phrases kept as lowercase strings; matching uses normalized document text.
FINANCE_KEYWORDS: tuple[str, ...] = (
    "stock",
    "market",
    "investment",
    "trading",
    "shares",
    "equity",
    "portfolio",
    "bank",
    "banking",
    "loan",
    "credit",
    "debit",
    "capital",
    "revenue",
    "profit",
    "loss",
    "tax",
    "economy",
    "inflation",
    "fund",
    "hedge",
    "dividend",
    "forex",
    "currency",
    "bond",
    "mutual fund",
    "financial",
    "analytics",
    "insurance",
    "accounting",
    "asset",
    "liability",
    "balance sheet",
    "cash flow",
    "earnings",
    "budget",
    "fiscal",
    "monetary",
    "interest rate",
    "cryptocurrency",
    "bitcoin",
    "fintech",
    "valuation",
    "broker",
    "commodity",
    "wealth",
    "economic growth",
    "gdp",
    "nasdaq",
    "nyse",
    "venture capital",
)

MEDICAL_KEYWORDS: tuple[str, ...] = (
    "patient",
    "hospital",
    "doctor",
    "treatment",
    "medicine",
    "diagnosis",
    "therapy",
    "infection",
    "virus",
    "bacteria",
    "disease",
    "surgery",
    "clinical",
    "healthcare",
    "pharmacy",
    "vaccine",
    "symptom",
    "cancer",
    "cardiology",
    "neurology",
    "radiology",
    "pathology",
    "epidemic",
    "pandemic",
    "blood pressure",
    "mri",
    "ct scan",
    "medical research",
    "biopsy",
    "prescription",
    "immunity",
    "genetics",
    "nursing",
    "anatomy",
    "physiology",
    "rehabilitation",
    "laboratory",
    "icu",
    "emergency care",
    "surgical",
    "oncology",
    "orthopedic",
    "dermatology",
    "pediatrics",
    "psychiatry",
    "microbiology",
    "public health",
    "patient care",
    "diagnostic",
)

TECHNOLOGY_KEYWORDS: tuple[str, ...] = (
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "neural network",
    "data science",
    "software",
    "hardware",
    "algorithm",
    "programming",
    "python",
    "java",
    "cloud computing",
    "cybersecurity",
    "database",
    "api",
    "automation",
    "robotics",
    "blockchain",
    "iot",
    "internet",
    "web development",
    "mobile app",
    "server",
    "frontend",
    "backend",
    "full stack",
    "devops",
    "gpu",
    "nlp",
    "computer vision",
    "big data",
    "analytics",
    "operating system",
    "linux",
    "windows",
    "react",
    "node.js",
    "tensorflow",
    "pytorch",
    "virtualization",
    "data mining",
    "ai model",
    "digital transformation",
    "microservices",
    "network",
    "encryption",
    "software engineering",
    "chatbot",
    "llm",
    "genai",
    "openai",
    # ML / CS courseware & engineering docs (reduce bleed into Medical from "neural"/"learning")
    "syllabus",
    "coursework",
    "curriculum",
    "lecture",
    "assignment",
    "semester",
    "credits",
    "marks",
    "grading",
    "tutorial",
    "convolutional",
    "recurrent",
    "transformer model",
    "attention mechanism",
    "backpropagation",
    "gradient descent",
    "loss function",
    "hyperparameter",
    "epoch",
    "batch size",
    "overfitting",
    "underfitting",
    "supervised learning",
    "unsupervised learning",
    "reinforcement learning",
    "dataset",
    "benchmark",
    "keras",
    "cuda",
    "jupyter",
    "github",
    "software stack",
    "deployment",
    "inference",
    "training loop",
    "neural architecture",
    "feedforward",
    "activation function",
    "tensor",
    "embedding",
    "tokenizer",
    "fine tuning",
    "pretrained",
)

SPORTS_KEYWORDS: tuple[str, ...] = (
    "football",
    "cricket",
    "basketball",
    "tennis",
    "volleyball",
    "athlete",
    "tournament",
    "championship",
    "league",
    "goal",
    "score",
    "match",
    "stadium",
    "coach",
    "player",
    "olympics",
    "fifa",
    "ipl",
    "batting",
    "bowling",
    "wicket",
    "soccer",
    "referee",
    "medal",
    "sportsmanship",
    "training",
    "fitness",
    "team",
    "captain",
    "competition",
    "race",
    "marathon",
    "swimming",
    "badminton",
    "hockey",
    "baseball",
    "rugby",
    "esports",
    "kabaddi",
    "wrestling",
    "boxing",
    "gymnastics",
    "cycling",
    "field event",
    "track event",
    "inning",
    "strike rate",
    "penalty",
    "world cup",
)

DOMAIN_KEYWORDS: dict[str, tuple[str, ...]] = {
    "Finance": FINANCE_KEYWORDS,
    "Medical": MEDICAL_KEYWORDS,
    "Technology": TECHNOLOGY_KEYWORDS,
    "Sports": SPORTS_KEYWORDS,
}


def validate_keyword_domains() -> None:
    missing = set(DOMAINS) - set(DOMAIN_KEYWORDS)
    if missing:
        raise ValueError(f"DOMAIN_KEYWORDS missing entries for: {missing}")


validate_keyword_domains()

# Placeholder for future Legal integration — wire into DOMAIN_KEYWORDS and DOMAINS.
LEGAL_KEYWORDS: tuple[str, ...] = ()
